### ISSUE TITLE
Please upgrade your package to the latest version of path provider ? and null safety please ?

### ISSUE THREAD

**Issue by PavieOlivier** [mateusfccp/magiceye#11] opened 2021-03-09 15:31 UTC

**Comment by mateusfccp** [comment] 2021-03-11 16:05
(Duplicate of #5)

@PavieOlivier The main reason that I still didn't migrate to _null-safety_ is that I made this package mainly to use it in an app for a company I work on, and we still didn't migrate to _null-safety_.

I started the work in the `v0.2` branch. However, _null-safety_ is not the only change the is coming to v0.2. There are some other major restructuring and support to flash and focus.

Thus, I think it won't be available too soon, but I will make the possible to finish this version by the end of the month.

Closing because of the duplicate.

**Closed as completed by mateusfccp** 2021-03-11 16:05 UTC
Labels: duplicate, enhancement
